POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "NEW TEST1234",
    "number": "555-666"
}

###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "",
    "number": "555-666"
}

###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "number": "555-666"
}

###

POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Testi Henkilö",
    "number": ""
}

###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Testi Henkilö"
}

###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Tt",
    "number": "555-666"
}
